language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
branches:  
  only:
    - master
before_script:
  - npm install -g bower
  - chmod a+x ./scripts/build.sh
script:
  - ./scripts/build.sh --quiet verify
before_deploy:
  - mkdir -p code-drop
  - pushd /home/travis/build/jmarsalis/bcca/ # need to be in the directory with appspec.yml so it will be at the root of the zip
  - zip -r /tmp/latest.zip /tmp/build-artifacts/* ./appspec.yml # appspec.yml has to be at the root of the package being created
  - popd
  - mv /tmp/latest.zip code-drop/latest.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: code-drop
  upload_dir: bcca-artifacts
  skip_cleanup: true
  on: &2
    repo: jmarsalis/bcca
  bucket: basecampcodingacademy
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: basecampcodingacademy
  key: bcca-artifacts/latest.zip
  bundle_type: zip
  application: Mercury
  deployment_group: BCCA
  region: us-east-1
  on: *2